### ISSUE TITLE
DOMContentLoaded hook?

### ISSUE THREAD

**Issue by s3ththompson** [ungoldman/choo-store#5]
I frequently find myself wanting to do a little initialization, change some state, or trigger a store event on `DOMContentLoaded`.

Would you consider providing some sort of hook from within the choo-store API to `DOMContentLoaded`? Or is this best accomplished by a vanilla store that requires choo-store actions, listens for `DOMContentLoaded`, and then fires them all off at once?

**Comment by ungoldman** [comment]
Hi @s3ththompson! Good question.

One of the trade-offs in the design of `choo-store` is that it's not easily accommodating to hooking into the following events:

```
DOMContentLoaded
DOMTitleChange​
navigate
popState
pushState
render
replaceState
```

I'm not sure what an unobtrusive or intuitive hook for those (global) events within a namespaced store might look like with the current `events.key` => `namespace:key` mapping.

I'm definitely open to providing something convenient to help with this if you have any ideas!

I'll mull it over and see if I can come up with something too (I am about to be on a 3 week vacation though so might be a while before I get back to this).

In the meantime I would probably just use a vanilla store for those core choo events as you mentioned above.

**Comment by s3ththompson** [comment]
What if you could "define" the global events within the events object and all the namespaced versions of the global events called when a given global event triggered?

e.g.

```js
module.exports = createStore({
  storeName: 'loadData',
  initialState: { loading: false },
  events: {
    DOMContentLoaded: ({store, emitter}) => {
      store.loading = true
      emitter.emit('render')
    }
  }
})
```

**Comment by ungoldman** [comment]
Yeah that seems reasonable enough -- just need to let people know about the "reserved event keywords" from the list above in the docs somewhere.

**Comment by s3ththompson** [comment]
Sounds good. If you think it's reasonable, I might create a PR.
